### ISSUE TITLE
不能打开项目文件夹

### ISSUE THREAD

**Issue by wilddylan** [Tencent/QMUI_Web_Desktop#1]
使用脚手架创建的项目
拖动到DesktopApp中会提示 招不到 UI_dev/config.json 应该是 js吧。
![2016-08-24 5 07 03](https://cloud.githubusercontent.com/assets/2519544/17924891/32a244ae-6a1d-11e6-945e-cdde9bec479b.png)
App是直接从官网下载的。

**Comment by wilddylan** [comment]
try {
    projectInfo = require(projectPath + '/UI_dev/config.json');
  } catch(e) {
    alert('没有找到 UI_dev/config.json，不是标准的 QMUI 项目');
  }

脚手架建立的项目中为 config.js 与 config.rb

**Comment by kayo5994** [comment]
谢谢你的反馈，已经更新了一个[新版本](https://github.com/QMUI/qmui_web_desktop/releases/tag/1.1.2)修复这个问题，官网的[分流下载](http://qmuiteam.com/web/index.html#downloadDirect)也同步更新了。
config.json 是旧式的配置表，更新了配置表格式后没有处理 App 的检测逻辑，所以导致了这个 bug。
