### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by shockw4ver** [Tencent/QMUI_Web_Desktop#2]
### 运行环境 ###

- [x] 操作系统版本：`macOS (10.x)`

### 具体问题描述 ###
* 迅雷出现“包含违规内容”的警告，无法下载。
* 官网下载链接404
#### 问题截图 ####
![1 pic](https://user-images.githubusercontent.com/17818522/31811774-6acede62-b546-11e7-8185-c8479aeb0da0.jpg)

**Comment by kayo5994** [comment]
感谢你的反馈，官网下载链接的问题已经修复，这边刚刚测试了迅雷下载是正常的，可以用官网下载地址再试一次。
